### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by yuanluow** [puzzlemoondev/BililiveRecorder-webhook-docker#50]
I hope to increase the conversion to mp4 format before uploading the recording (because PR and some editing software cannot recognize the flv format), create a folder corresponding to the date when uploading, and delete the pre and post conversion files after uploading. I can also choose whether to upload the. json format log (if it is currently possible, it may be my problem)

**Comment by puzzlemoondev** [comment]
For now, mp4 conversion only happens when you turn on the burn danmaku flag. Since I develop this for running on some cheap cloud machine, I regret ever adding that feature. It just takes so much computation resource and it does not make sense for me to rent a costly compute optimized instance just for bililive recorder.
So if you ask me, you should do that locally. But you can always open a pull request and I'll be willing to merge it.

To answer your JSON log question, it's there because file name does not contain enough information about the recording. We can probably add an environment flag to turn that off.

**Comment by yuanluow** [comment]
I tried using some sh scripts to convert to mp4 and compress to zip (which can be omitted). After recording, I executed MaxProcess.sh to complete the conversion format and compression, But I don't know how to change the upload file of aliyunpan/baiduyunpan (I can't modify the uploaded file from dockerfile, I hope you can give me some hints, just indicate how to modify the uploaded file and path. Thank you. The script has been uploaded together, and I hope it will be helpful to you
[BilIUP.zip](https://github.com/puzzlemoondev/BililiveRecorder-webhook-docker/files/11712597/BilIUP.zip)

**Comment by puzzlemoondev** [comment]
Sorry that it took me so long to reply. I was busy with my own stuff.
I've added the feature to customize the upload folder. Don't know if that's what you want.

**Comment by yuanluow** [comment]
Thank you, yes. Uploading to the specified folder is what I need. I hope you can add how to set the upload folder in the readme or bilibili columns. For example, if the folder name is XXX, it needs to be written as ALIYUNPAN_ UPLOAD_ DIR=XXX, still write ALIYUNPAN_ UPLOAD_ DIR=654a5901c50de2d(The folder ID is in the folder/654a5901c50de2d of the Alibaba Cloud Cloud disk web version). I hope you can clarify how to write the upload folder parameters

**Comment by puzzlemoondev** [comment]
path can be absolute or relative. if it's relative then / is prepended. if it's absolute then then path is preserved. if it's not working as intended then there's a bug. I don't have aliyunpan so I can't debug. can you clarify the expected & actual behavior on aliyunpan?
